platform :ios, '12.0'
inhibit_all_warnings!   #去掉pod里的所有警告
use_frameworks!


target 'iphoneCom' do
  #pod 'YYModel'
  #pod 'YYImage'
  #pod 'YYCache'
  #pod 'YYWebImage'
  #pod 'YYText'
  pod 'YYKit'
  pod "AFNetworking"
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'Kingfisher' # 图片加载
  pod 'SnapKit'
  
  pod 'KVOController' #安全KVO
  pod 'FMDB'
  
  #pod 'FBMemoryProfiler'
  #pod 'FBAllocationTracker'
  #pod 'FBRetainCycleDetector'
  
  
  pod 'YDSwift', :path => '../Module/YDSwift/YDSwift.podspec'
  pod 'YDLearn', :path => '../Module/YDLearn/YDLearn.podspec'
  
end

