platform :ios, '10.0'
inhibit_all_warnings!   #去掉pod里的所有警告


target 'iphoneCom' do
  pod 'Alamofire'
  pod 'HandyJSON'
  pod 'FMDB'  # SQLite
  pod 'Kingfisher' # 图片加载
  pod 'MJRefresh' # 下拉刷新
  pod 'SVProgressHUD' # 遮罩loading
  pod 'MarqueeLabel' # 跑马灯Label
  pod 'SnapKit' # Swift3.x 用 3.x； Swift4.x 用4.x
  pod 'SSZipArchive'
  pod 'WebViewJavascriptBridge', '~> 6.0' # webview接口互调
  pod 'YYImage'
  pod 'YYText'
end
